#!/bin/bash

extman(){
    echo "1.Search for \"User Themes\" in the \"Browse\" tab"
    echo "2.Click the \"Add\" button to install"
    echo "3.Go to the "Added" tab and activate the Extension by setting the button on the header to \"ON\" (to the right)"
    echo "4.turn on the button to the right of \"User Themes\""
extension-manager 2> /dev/null
}

# Main
echo "Install gnome-shell-manager"
dpkg -s gnome-shell-extension-manager >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
  sudo apt -y install gnome-shell-extension-manager >/dev/null 2>/dev/null
  echo "done"
  echo ""
  else
      echo "Already Installed"
fi
echo "--Please set extention-manager--"
extman;
echo "thank you!"
echo " activate user-theme"
sudo cp ~/.local/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com/schemas/org.gnome.shell.extensions.user-theme.gschema.xml /usr/share/glib-2.0/schemas && sudo glib-compile-schemas /usr/share/glib-2.0/schemas
exit 0

